/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Cita;
import Modelo.DAO.DBConnection;
import java.awt.BorderLayout;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author SALVADOR
 */
public class Confirmar_Cita2 extends javax.swing.JPanel {
    //Panel2
    private Cita cita;
    private javax.swing.JPanel panelPadre;
    public Confirmar_Cita2(Cita cita, javax.swing.JPanel panelPadre) {
        initComponents();
        this.cita=cita;
        this.panelPadre = panelPadre;
        comboDoctores.setEnabled(false); // al iniciar
        comboHoras.setEnabled(false);
        java.util.Date fecha_hoy=new java.util.Date();
        Calendario_Cita.setMinSelectableDate(fecha_hoy);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Calendario_Cita = new com.toedter.calendar.JCalendar();
        jLabel5 = new javax.swing.JLabel();
        comboCita = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        comboArea = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        comboDoctores = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        comboHoras = new javax.swing.JComboBox<>();
        SiguienteButton = new javax.swing.JToggleButton();
        BtnRegresar = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 175, 185));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione la fecha de la cita:");

        jLabel6.setBackground(new java.awt.Color(255, 204, 204));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("¡No olvides establecer una fecha!");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ingresa la cita que quieres realizar:");

        comboCita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Control", "Síntoma en Específico" }));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Seleccione el Area a Elegir:");

        comboArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oncologia", "Neurologia", "Gastroenterologia", "Hepatologia", "Medicina General" }));
        comboArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAreaActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Seleccione el doctor que quiera que le atienda:");

        comboDoctores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDoctores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDoctoresActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccione la Hora:");

        comboHoras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00" }));

        SiguienteButton.setBackground(new java.awt.Color(168, 218, 220));
        SiguienteButton.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        SiguienteButton.setText("Siguiente");
        SiguienteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SiguienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteButtonActionPerformed(evt);
            }
        });

        BtnRegresar.setBackground(new java.awt.Color(168, 218, 220));
        BtnRegresar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        BtnRegresar.setText("Regresar  ");
        BtnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(SiguienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(BtnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboArea, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboCita, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboDoctores, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(comboHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 25, Short.MAX_VALUE)))))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(Calendario_Cita, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Calendario_Cita, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDoctores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiguienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void cargarDoctoresPorArea(String area) {
    try {
        try (Connection con = DBConnection.getInstancia1().getConexion()) {
            CallableStatement cs = con.prepareCall("{CALL MostrarDoctoresPorArea(?)}");
            cs.setString(1, area);
            ResultSet rs = cs.executeQuery();
            comboDoctores.removeAllItems();
            while (rs.next()) {
                comboDoctores.addItem(rs.getString("NombreCompleto"));
            }
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al cargar doctores desde el procedimiento: " + ex.getMessage());
    }
}
    private void comboAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAreaActionPerformed
        Object seleccionado = comboArea.getSelectedItem();
        if (seleccionado != null) {
            String areaSeleccionada = seleccionado.toString();
            cargarDoctoresPorArea(areaSeleccionada);
            comboDoctores.setEnabled(true);
        }
    }//GEN-LAST:event_comboAreaActionPerformed

    private void comboDoctoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDoctoresActionPerformed
        Object seleccionado = comboDoctores.getSelectedItem();
        if (seleccionado != null) {
            String doctorSeleccionado = seleccionado.toString();
            cargaHorasDisponibles(doctorSeleccionado);
            comboHoras.setEnabled(true);
        }
    }//GEN-LAST:event_comboDoctoresActionPerformed

    private void SiguienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteButtonActionPerformed

        if(Calendario_Cita.getDate()==null){
            JOptionPane.showMessageDialog(null, "No puede avanzar porque le falta completar "
                + "un espacio de texto",
                "Error al avanzar", JOptionPane.ERROR_MESSAGE);
        }
        else{
            double precio;
            String texto_Area=comboArea.getSelectedItem().toString();
            String DNI="";
            try {
                try (Connection con = DBConnection.getInstancia1().getConexion()) {
                    CallableStatement cs = con.prepareCall("{CALL MostrarDNI(?)}");
                    cs.setString(1, comboDoctores.getSelectedItem().toString());
                    ResultSet rs = cs.executeQuery();
                    while (rs.next()) {
                        DNI=rs.getString("DNI");
                    }
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error al cargar doctores desde el procedimiento: " + ex.getMessage());
            }
            cita.setDNI_Medico(DNI);
            cita.setArea_Elegida(texto_Area);
            cita.setFecha(obtenerFechaSeleccionada());
            cita.setHora(comboHoras.getSelectedItem().toString());
            cita.setEvaluacion_Realizada(comboCita.getSelectedItem().toString());
            if(cita.getArea_Elegida().equals("Neurologia") || cita.getArea_Elegida().equals("Oncologia")){
                precio=65.4;
            }
            else{
                precio=34;
            }
            cita.setPrecio(precio);
            cita.setNombre_Completo_Medico(comboDoctores.getSelectedItem().toString());
        }
        cambiaraPrecioEM2();
    }//GEN-LAST:event_SiguienteButtonActionPerformed

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        /*Boton para regresar a la ventana principal*/
        this.setVisible(false);
        cambiaraDatos_Generales();
    }//GEN-LAST:event_BtnRegresarActionPerformed

    public void cargaHorasDisponibles(String doctorSeleccionado) {
        try {
            try (Connection con = DBConnection.getInstancia1().getConexion() // Tu clase de conexión
            ) {
                CallableStatement cs = con.prepareCall("{CALL MostrarTurnoDoctor(?)}");
                cs.setString(1, doctorSeleccionado);
                ResultSet rs = cs.executeQuery();
                comboHoras.removeAllItems();
                while (rs.next()) {
                    if(rs.getString("Turno_Perteneciente").equals("Manana")){
                        comboHoras.addItem("08:00");
                        comboHoras.addItem("09:00");
                        comboHoras.addItem("10:00");
                        comboHoras.addItem("11:00");
                        comboHoras.addItem("12:00");
                    }
                    if(rs.getString("Turno_Perteneciente").equals("Tarde")){
                        comboHoras.addItem("14:00");
                        comboHoras.addItem("15:00");
                        comboHoras.addItem("16:00");
                        comboHoras.addItem("17:00");
                        comboHoras.addItem("18:00");
                    }
                }
            }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al cargar turnos desde el procedimiento: " + ex.getMessage());
    }
    }

    private Date obtenerFechaSeleccionada() {
       return new java.sql.Date(Calendario_Cita.getDate().getTime());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegresar;
    private com.toedter.calendar.JCalendar Calendario_Cita;
    private javax.swing.JToggleButton SiguienteButton;
    private javax.swing.JComboBox<String> comboArea;
    private javax.swing.JComboBox<String> comboCita;
    private javax.swing.JComboBox<String> comboDoctores;
    private javax.swing.JComboBox<String> comboHoras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    private void cambiaraPrecioEM2() {
                // Obtener el contenedor padre (JFrame o JPanel principal)
        java.awt.Container parent = this.getParent();
        
        // Remover este panel
        parent.remove(this);
        
        // Crear y agregar el nuevo panel
        PrecioEM2 ZonaPrecio = new PrecioEM2(cita, panelPadre);
        parent.add(ZonaPrecio,BorderLayout.CENTER);
        
        // Actualizar la interfaz
        parent.revalidate();
        parent.repaint();
    }
        private void cambiaraDatos_Generales() {
                // Obtener el contenedor padre (JFrame o JPanel principal)
        java.awt.Container parent = this.getParent();
        
        // Remover este panel
        parent.remove(this);
        
        // Crear y agregar el nuevo panel
        Datos_Generales dag1 = new Datos_Generales(cita, panelPadre);
        parent.add(dag1,BorderLayout.CENTER);
        
        // Actualizar la interfaz
        parent.revalidate();
        parent.repaint();
    }
}
