/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista; 

/**
 *
 * @author Itzair
 */
public class ConsejoRutinaFisica extends javax.swing.JPanel {
    
    private javax.swing.JPanel contenedorPrincipal;

    public ConsejoRutinaFisica(javax.swing.JPanel contenedorPrincipal) {
        this.contenedorPrincipal = contenedorPrincipal;
        initComponents();

        comboArea1.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int indexArea = comboArea1.getSelectedIndex();
                if (indexArea >= 0 && indexArea <= 4) {
                    comboRutina.setSelectedIndex(indexArea);
                }
            }
        });
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboArea1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboRutina = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsejo = new javax.swing.JTextArea();
        SiguienteButton = new javax.swing.JToggleButton();
        BtnRegresar = new javax.swing.JButton();
        MostrarConsejo = new javax.swing.JToggleButton();
        setBackground(new java.awt.Color(0, 175, 185));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONSEJOS Y ACTIVIDADES FISICAS RECOMENDADAS ");

        comboArea1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oncologia", "Neurologia", "Gastroenterologia", "Hepatologia", "Medicina General" }));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Selecciona el Area Registrada:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Eliga la rutina física:");

        comboRutina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rutina de Rehabilitación", "Rutina de Equilibrio y Nueroplasticidad", "Rutina Antiinflamatoria Intestinal", "Rutina de Oxigenación y Regeneración Hepática", "Rutina de Salud Metabólica y Cardiovascular" }));
        comboRutina.setToolTipText("");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Consejo en base a su rutina física: ");

        txtConsejo.setColumns(20);
        txtConsejo.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        txtConsejo.setRows(5);
        jScrollPane1.setViewportView(txtConsejo);

        SiguienteButton.setBackground(new java.awt.Color(168, 218, 220));
        SiguienteButton.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        SiguienteButton.setText("Siguiente");
        SiguienteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SiguienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteButtonActionPerformed(evt);
            }
        });
        BtnRegresar.setBackground(new java.awt.Color(168, 218, 220));
        BtnRegresar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        BtnRegresar.setText("Regresar  ");
        BtnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        MostrarConsejo.setBackground(new java.awt.Color(168, 218, 220));
        MostrarConsejo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        MostrarConsejo.setText("Realizar Consejo");
        MostrarConsejo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MostrarConsejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarConsejoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
   layout.setHorizontalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(layout.createSequentialGroup()
        .addGap(18, 18, 18)
        .addComponent(jLabel1)
        .addContainerGap(14, Short.MAX_VALUE))
    .addGroup(layout.createSequentialGroup()
        .addGap(31, 31, 31)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboRutina, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(MostrarConsejo)
                        .addGap(47, 47, 47)
                        .addComponent(SiguienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(BtnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
));
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboRutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SiguienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MostrarConsejo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SiguienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteButtonActionPerformed
                                                
    contenedorPrincipal.removeAll();
    contenedorPrincipal.setLayout(new java.awt.BorderLayout());

    PlanAlimentaciónSalud panelAlimentacion = new PlanAlimentaciónSalud(contenedorPrincipal);
    contenedorPrincipal.add(panelAlimentacion, java.awt.BorderLayout.CENTER);

    contenedorPrincipal.revalidate();
    contenedorPrincipal.repaint();

    }//GEN-LAST:event_SiguienteButtonActionPerformed

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
       
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void MostrarConsejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarConsejoActionPerformed
      String area = comboArea1.getSelectedItem().toString();
        String rutina = comboRutina.getSelectedItem().toString(); 

        String consejo = switch (rutina) {
            case "Rutina de Rehabilitación" ->
                "Ideal para pacientes de " + area + ". Realice ejercicios suaves como caminar, estiramientos asistidos o movimientos articulares lentos.";
            case "Rutina de Equilibrio y Nueroplasticidad" -> 
                "Recomendada para " + area + ". Incluye ejercicios de coordinación, equilibrio con una pierna y actividades mentales activas.";
            case "Rutina Antiinflamatoria Intestinal" ->
                "En " + area + " se sugiere hacer respiración profunda, caminatas cortas después de comer y evitar movimientos bruscos.";
            case "Rutina de Oxigenación y Regeneración Hepática" ->
                "Incluye ejercicios de respiración, caminatas suaves al aire libre y posturas de relajación para pacientes de " + area + ".";
            case "Rutina de Salud Metabólica y Cardiovascular" ->
                "Para pacientes de " + area + ": realice caminatas de 30 min, bicicleta estática o ejercicios aeróbicos de bajo impacto.";
            default -> "Seleccione una rutina válida."; 
        };

       txtConsejo.setText(consejo);  
    }//GEN-LAST:event_MostrarConsejoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JToggleButton MostrarConsejo;
    private javax.swing.JToggleButton SiguienteButton;
    private javax.swing.JComboBox<String> comboArea1;
    private javax.swing.JComboBox<String> comboRutina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtConsejo;
    // End of variables declaration//GEN-END:variables
}
