/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.Component;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author SALVADOR
 */
public class Obsevar_NotificacionesHechas extends javax.swing.JPanel {
    DefaultTableModel modelo =  new DefaultTableModel();
    public Obsevar_NotificacionesHechas() {
        initComponents();
        configurarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Notificaciones = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 175, 185));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Historial de Notificaciones hechas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese aqui su DNI:");

        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });

        Tabla_Notificaciones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tabla_Notificaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Notificacion_Num", "DNI_Personal", "Origen", "Destinatario", "Fecha", "Mensaje", "Motivo"
            }
        ));
        Tabla_Notificaciones.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jScrollPane1.setViewportView(Tabla_Notificaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(63, 63, 63)
                .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIActionPerformed
     private void configurarTabla() {
        modelo.setColumnIdentifiers(new String[]{
            "ID Historial", "ID Medico", "Fecha", 
            "Resultado", "Recomendacion", "Tipo"
        });
        Tabla_Notificaciones.setModel(modelo);
        
        // Configurar renderizador para texto multilínea
        Tabla_Notificaciones.setDefaultRenderer(Object.class, new MultiLineCellRenderer());
    }
     private class MultiLineCellRenderer extends JTextArea implements TableCellRenderer {
        public MultiLineCellRenderer() {
            setLineWrap(true);
            setWrapStyleWord(true);
            setOpaque(true);
            setBorder(BorderFactory.createEmptyBorder(2, 4, 2, 4));
            setFont(Tabla_Notificaciones.getFont());
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            // Configurar texto y colores
            setText(value != null ? value.toString() : "");
            
            if (isSelected) {
                setBackground(table.getSelectionBackground());
                setForeground(table.getSelectionForeground());
            } else {
                setBackground(table.getBackground());
                setForeground(table.getForeground());
            }
            
            // Calcular altura necesaria para esta celda
            int anchoColumna = table.getColumnModel().getColumn(column).getWidth();
            setSize(new Dimension(anchoColumna, Integer.MAX_VALUE));
            int alturaPreferida = getPreferredSize().height + 4;
            
            // Ajustar altura de fila si es necesario
            if (table.getRowHeight(row) < alturaPreferida) {
                table.setRowHeight(row, Math.min(alturaPreferida, 300)); // Límite máximo de 300px
            }
            
            return this;
        }
    }
    public void ajustarAltosFilas() {
        Tabla_Notificaciones.setAutoCreateRowSorter(false); // Mejorar rendimiento
        
        for (int fila = 0; fila < Tabla_Notificaciones.getRowCount(); fila++) {
            int maxAltura = 30; // Altura mínima
            
            for (int columna = 0; columna < Tabla_Notificaciones.getColumnCount(); columna++) {
                Component comp = Tabla_Notificaciones.prepareRenderer(
                    Tabla_Notificaciones.getCellRenderer(fila, columna), fila, columna);
                
                maxAltura = Math.max(maxAltura, comp.getPreferredSize().height + 4);
            }
            
            Tabla_Notificaciones.setRowHeight(fila, Math.min(maxAltura, 300)); // Límite de 300px
        }
        
        Tabla_Notificaciones.setAutoCreateRowSorter(true);
    }
    
    public void prepararTabla() {
        modelo.setRowCount(0); // Limpiar tabla sin recrear el modelo
    }
    
    public void agregarFila(Object[] datos) {
        modelo.addRow(datos);
    }
    
    public void datosCargados() {
        SwingUtilities.invokeLater(this::ajustarAltosFilas);
    }
    
    public JTextField getTxtDNI() {
        return txtDNI;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_Notificaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDNI;
    // End of variables declaration//GEN-END:variables
}
