/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ObservadorEventoPreventivo;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import Controlador.ObservadorRecordatorio;

/**
 *
 * @author LAB-USR-LNORTE
 */
public class PanelNotificaciones extends javax.swing.JPanel {
    private final Color COLOR_POR_DEFECTO = new Color(0,0,0,0); // O usa null para transparente
    private final Color COLOR_SELECCIONADO = new Color(153, 217, 140);
    private String panel_Activo;
    private Recordatorio_Citas rc1; 
    private NotificacionEventosMedicos nem1;
    private List<ObservadorRecordatorio> observadores=new ArrayList<>();
    private List<ObservadorEventoPreventivo> observadores2=new ArrayList<>();
    private JButton botonSeleccionadoActual = null;
    public PanelNotificaciones() {
        initComponents();
        configurarBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Notificar_Eventos = new javax.swing.JButton();
        Enviar_recordatorios = new javax.swing.JButton();
        Historial_observacionesBtn = new javax.swing.JButton();
        contenedor = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        Boton_Aceptar = new javax.swing.JButton();

        setBackground(new java.awt.Color(85, 143, 178));
        setPreferredSize(new java.awt.Dimension(836, 639));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Zona de Notificaciones");

        Notificar_Eventos.setText("Notificar eventos medicos");
        Notificar_Eventos.setBorder(null);
        Notificar_Eventos.setContentAreaFilled(false);
        Notificar_Eventos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Notificar_Eventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Notificar_EventosActionPerformed(evt);
            }
        });

        Enviar_recordatorios.setText("Enviar recordatorios");
        Enviar_recordatorios.setBorder(null);
        Enviar_recordatorios.setContentAreaFilled(false);
        Enviar_recordatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Enviar_recordatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enviar_recordatoriosActionPerformed(evt);
            }
        });

        Historial_observacionesBtn.setText("<html>Mostrar historial de <br>evaluaciones</html>");
        Historial_observacionesBtn.setBorder(null);
        Historial_observacionesBtn.setContentAreaFilled(false);
        Historial_observacionesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Historial_observacionesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Historial_observacionesBtnActionPerformed(evt);
            }
        });

        contenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        jButton2.setBackground(new java.awt.Color(218, 131, 136));
        jButton2.setText("<html>Cancelar y cerrar <br>el programa</html>");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Boton_Aceptar.setBackground(new java.awt.Color(138, 192, 102));
        Boton_Aceptar.setText("Aceptar");
        Boton_Aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_AceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Notificar_Eventos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Enviar_recordatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Historial_observacionesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(Boton_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 56, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Notificar_Eventos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Enviar_recordatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Historial_observacionesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Notificar_EventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Notificar_EventosActionPerformed
        seleccionarBoton(Notificar_Eventos);
        panel_Activo="EventoMedico";
        Boton_Aceptar.setVisible(true);
        nem1=new NotificacionEventosMedicos();
        contenedor.removeAll();
        contenedor.setLayout(new BorderLayout());
        contenedor.add(nem1,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_Notificar_EventosActionPerformed

    private void Enviar_recordatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enviar_recordatoriosActionPerformed
        seleccionarBoton(Enviar_recordatorios);
        Boton_Aceptar.setVisible(true);
        panel_Activo="Enviar_Recordatorio";//Indica que panel se esta usando
        Boton_Aceptar.setVisible(true);
        rc1 = new Recordatorio_Citas();
        contenedor.removeAll();
        contenedor.setLayout(new BorderLayout());
        contenedor.add(rc1,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_Enviar_recordatoriosActionPerformed

    private void Historial_observacionesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Historial_observacionesBtnActionPerformed
        seleccionarBoton(Historial_observacionesBtn);
        Boton_Aceptar.setVisible(true);
    }//GEN-LAST:event_Historial_observacionesBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int valor=JOptionPane.showConfirmDialog(null,"¿Deseas cancelar y cerrar todo?","Alerta",JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Boton_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_AceptarActionPerformed
        int valor=JOptionPane.showConfirmDialog(null,"¿Deseas realizar esta operacion?",
            "Alerta",JOptionPane.YES_NO_OPTION);
             if(valor==0){
            switch(panel_Activo){
                case "EventoMedico":
                    EnviarNotificacion2();
                    break;
                case "Enviar_Recordatorio":
                    EnviarNotificacion();
                    break;
            }
        }
    }//GEN-LAST:event_Boton_AceptarActionPerformed
private void seleccionarBoton(JButton boton) {
    if (boton == null) return; // Seguridad

    // Restaura el botón anterior
    if (botonSeleccionadoActual != null) {
        botonSeleccionadoActual.setBackground(COLOR_POR_DEFECTO);
        botonSeleccionadoActual.setOpaque(false);
        botonSeleccionadoActual.setContentAreaFilled(false);
    }

    // Selecciona el nuevo botón
    boton.setBackground(COLOR_SELECCIONADO);
    boton.setContentAreaFilled(true);
    boton.setOpaque(true);
    botonSeleccionadoActual = boton;
}
private void configurarBotones() {
    // Lista de todos los botones que cambiarán de color
    JButton[] botones = {
        Enviar_recordatorios,Historial_observacionesBtn,Notificar_Eventos
    };

    for (JButton boton : botones) {
        boton.setOpaque(false); 
        boton.setBorderPainted(false); 
        boton.setContentAreaFilled(false);
    }
}
public void AgregarPaciente(ObservadorRecordatorio o){
    observadores.add(o);
}
public void AgregarPaciente2(ObservadorEventoPreventivo oep){
    observadores2.add(oep);
}
public  void EnviarNotificacion(){
    String DNI=JOptionPane.showInputDialog("Ingrese su DNI:");
    String origen=rc1.getOrigen();
    String destinatario=rc1.getDestinatario();
    String mensaje=rc1.getMensaje();
    for(ObservadorRecordatorio o:observadores){
        o.actualizar(origen, destinatario, mensaje);
    }
    JOptionPane.showMessageDialog(this,"Notificacion de recordatorio enviada");
    try{
       int resultado;
       Connection con = DBConnection.getInstancia1().getConexion();
       CallableStatement stmt=null;
       stmt=con.prepareCall("CALL  insertarNotificaciones(?,?,?,?,?,?)");
       stmt.setString(1, DNI);
       stmt.setString(2,origen);
       stmt.setString(3,destinatario);
       stmt.setDate(4, rc1.getFecha());
       stmt.setString(5,mensaje);
       stmt.setString(6, "Recordatorio de Cita");
       resultado=stmt.executeUpdate();
       if(resultado==0){
           JOptionPane.showMessageDialog(null, "La notificacion no se pudo guardar.");
       }
       else{
           JOptionPane.showMessageDialog(null,"La notificacion fue guardada tambien en la base de datos");
       }
    }catch(SQLException ex){
        JOptionPane.showMessageDialog(null, "Error al manejar la base de datos");
    }
}
public void EnviarNotificacion2(){
   String DNI2=JOptionPane.showInputDialog("Ingrese su DNI:");
   String origen=nem1.getOrigen();
   String destinatario=nem1.getDestino();
   String motivo=nem1.getEventoMedico();
   String mensaje=nem1.getMensaje();
   for(ObservadorEventoPreventivo o:observadores2){
       o.actualizar(origen, destinatario, motivo, mensaje);
   }
   JOptionPane.showMessageDialog(this,"Notificacion de evento medico");
      try{
       int resultado;
       Connection con = DBConnection.getInstancia1().getConexion();
       CallableStatement stmt=null;
       stmt=con.prepareCall("CALL  insertarNotificaciones(?,?,?,?,?,?)");
       stmt.setString(1, DNI2);
       stmt.setString(2,origen);
       stmt.setString(3,destinatario);
       stmt.setDate(4, nem1.getFecha());
       stmt.setString(5,mensaje);
       stmt.setString(6, nem1.getMotivo());
       resultado=stmt.executeUpdate();
       if(resultado==0){
           JOptionPane.showMessageDialog(null, "La notifiacion no se pudo guardar.");
       }
       else{
           JOptionPane.showMessageDialog(null,"La notificacion fue guardada tambien en la base de datos");
       }
    }catch(SQLException ex){
        JOptionPane.showMessageDialog(null, "Error al manejar la base de datos");
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Aceptar;
    private javax.swing.JButton Enviar_recordatorios;
    private javax.swing.JButton Historial_observacionesBtn;
    private javax.swing.JButton Notificar_Eventos;
    private javax.swing.JPanel contenedor;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
