/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.CRUDPaciente;
import Controlador.PacienteFactory;
import Modelo.Cita;
import Modelo.Paciente;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author LAB-USR-LNORTE
 */
public class PanelPacientes extends javax.swing.JPanel {
    private final Color COLOR_POR_DEFECTO = new Color(0,0,0,0); // O usa null para transparente
    private final Color COLOR_SELECCIONADO = new Color(153, 217, 140);
    private String panel_Activo;
    private JButton botonSeleccionadoActual = null;
    private Cita cita;
    public PanelPacientes(Cita cita) {
        initComponents();
        configurarBotones();
        this.cita=cita;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RegistrarseP_btn = new javax.swing.JButton();
        RealizarCita_btn = new javax.swing.JButton();
        Observar_Historialbtn = new javax.swing.JButton();
        contenedor2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        Boton_Aceptar = new javax.swing.JButton();

        setBackground(new java.awt.Color(85, 143, 178));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Zona de Pacientes");

        RegistrarseP_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registro.png"))); // NOI18N
        RegistrarseP_btn.setText("<html>Registrarse como <br>Paciente</html>");
        RegistrarseP_btn.setBorder(null);
        RegistrarseP_btn.setContentAreaFilled(false);
        RegistrarseP_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegistrarseP_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarseP_btnActionPerformed(evt);
            }
        });

        RealizarCita_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cita.png"))); // NOI18N
        RealizarCita_btn.setText("Realizar Cita");
        RealizarCita_btn.setBorder(null);
        RealizarCita_btn.setContentAreaFilled(false);
        RealizarCita_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RealizarCita_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarCita_btnActionPerformed(evt);
            }
        });

        Observar_Historialbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Observar_Historial.png"))); // NOI18N
        Observar_Historialbtn.setText("Observar Historial");
        Observar_Historialbtn.setBorder(null);
        Observar_Historialbtn.setContentAreaFilled(false);
        Observar_Historialbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Observar_Historialbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Observar_HistorialbtnActionPerformed(evt);
            }
        });

        contenedor2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout contenedor2Layout = new javax.swing.GroupLayout(contenedor2);
        contenedor2.setLayout(contenedor2Layout);
        contenedor2Layout.setHorizontalGroup(
            contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        contenedor2Layout.setVerticalGroup(
            contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        jButton2.setBackground(new java.awt.Color(218, 131, 136));
        jButton2.setText("<html>Cancelar y cerrar <br>el programa</html>");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Boton_Aceptar.setBackground(new java.awt.Color(138, 192, 102));
        Boton_Aceptar.setText("Aceptar");
        Boton_Aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_AceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RealizarCita_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegistrarseP_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Observar_Historialbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(contenedor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Boton_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(RegistrarseP_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RealizarCita_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Observar_Historialbtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(contenedor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2)
                            .addComponent(Boton_Aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarseP_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarseP_btnActionPerformed
        seleccionarBoton(RegistrarseP_btn);
        Boton_Aceptar.setVisible(true);
        Registrar_Paciente r1=new Registrar_Paciente();
        panel_Activo="registrarse";
        contenedor2.removeAll(); // Limpia el contenedor
        contenedor2.setLayout(new BorderLayout());
        contenedor2.add(r1, BorderLayout.CENTER); // Agrega el nuevo panel
        contenedor2.revalidate(); // Revalida el layout
        contenedor2.repaint();    // Redibuja el contenedor
    }//GEN-LAST:event_RegistrarseP_btnActionPerformed

    private void RealizarCita_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarCita_btnActionPerformed
        seleccionarBoton(RealizarCita_btn);
        Boton_Aceptar.setVisible(false);
        Datos_Generales d1=new Datos_Generales(cita,contenedor2);
        contenedor2.removeAll(); // Limpia el contenedor
        contenedor2.setLayout(new BorderLayout());
        contenedor2.add(d1, BorderLayout.CENTER); // Agrega el nuevo panel
        contenedor2.revalidate(); // Revalida el layout
        contenedor2.repaint();    // Redibuja el contenedor
    }//GEN-LAST:event_RealizarCita_btnActionPerformed

    private void Observar_HistorialbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Observar_HistorialbtnActionPerformed
        seleccionarBoton(Observar_Historialbtn);
        Boton_Aceptar.setVisible(true);
        contenedor2.removeAll(); // Limpia el contenedor
        contenedor2.setLayout(new BorderLayout());
        contenedor2.add(new JPanel(), BorderLayout.CENTER); // Agrega el nuevo panel
        contenedor2.revalidate(); // Revalida el layout
        contenedor2.repaint();    // Redibuja el contenedor
    }//GEN-LAST:event_Observar_HistorialbtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int valor=JOptionPane.showConfirmDialog(null,"¿Deseas cancelar y cerrar todo?","Alerta",JOptionPane.YES_NO_OPTION);
        if(valor==0){
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Boton_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_AceptarActionPerformed
        int valor=JOptionPane.showConfirmDialog(null,"¿Deseas realizar esta operacion?",
            "Alerta",JOptionPane.YES_NO_OPTION);
        if(valor==0){
            switch(panel_Activo){
                case "registrarse":
                insertarPaciente();
                break;
            }
        }
    }//GEN-LAST:event_Boton_AceptarActionPerformed

    private void seleccionarBoton(JButton boton) {
    if (boton == null) return; // Seguridad

    // Restaura el botón anterior
    if (botonSeleccionadoActual != null) {
        botonSeleccionadoActual.setBackground(COLOR_POR_DEFECTO);
        botonSeleccionadoActual.setOpaque(false);
        botonSeleccionadoActual.setContentAreaFilled(false);
    }

    // Selecciona el nuevo botón
    boton.setBackground(COLOR_SELECCIONADO);
    boton.setContentAreaFilled(true);
    boton.setOpaque(true);
    botonSeleccionadoActual = boton;
}
private void insertarPaciente() {
        try{
           Registrar_Paciente panelpaciente=(Registrar_Paciente) contenedor2.getComponent(0);
           Paciente paciente2=panelpaciente.getPacienteFromForm();
           guardarPacienteenBD(paciente2);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error en formato numérico: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
private void guardarPacienteenBD(Paciente paciente) {
       CRUDPaciente operacion = PacienteFactory.establecerOperacion("insertar", paciente);
       int resultado = operacion.actuar();
       if (resultado > 0) {
        JOptionPane.showMessageDialog(this, "Registro realizado correctamente");
       } else {
        JOptionPane.showMessageDialog(this, "Error al registrar al paciente");
       }
    }
private void configurarBotones() {
    // Lista de todos los botones que cambiarán de color
    JButton[] botones = {
        RegistrarseP_btn, RealizarCita_btn,
        Observar_Historialbtn
    };

    for (JButton boton : botones) {
        boton.setOpaque(false); 
        boton.setBorderPainted(false); 
        boton.setContentAreaFilled(false);
    }
}
public void mostrarPanelCitas() {
    seleccionarBoton(RealizarCita_btn);
    seleccionarBoton(RealizarCita_btn);  // Opcional si quieres que se marque
    Boton_Aceptar.setVisible(true);
    Datos_Generales d1 = new Datos_Generales(cita, contenedor2);
    contenedor2.removeAll();
    contenedor2.setLayout(new BorderLayout());
    contenedor2.add(d1, BorderLayout.CENTER);
    contenedor2.revalidate();
    contenedor2.repaint();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Aceptar;
    private javax.swing.JButton Observar_Historialbtn;
    private javax.swing.JButton RealizarCita_btn;
    private javax.swing.JButton RegistrarseP_btn;
    private javax.swing.JPanel contenedor2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
