/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista; 

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import Vista.ConsejoRutinaFisica; 


/**
 *
 * @author LAB-USR-LNORTE
 */
public class PanelBienestar extends javax.swing.JPanel {
    private final Color COLOR_POR_DEFECTO = new Color(0,0,0,0); // O usa null para transparente
    private final Color COLOR_SELECCIONADO = new Color(153, 217, 140);
    private String panel_Activo;
    private JButton botonSeleccionadoActual = null;
    public PanelBienestar() {
        initComponents();
        configurarBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        GenerarRec_btn = new javax.swing.JButton();
        Rutina_actividades_btn = new javax.swing.JButton();
        Plan_de_alimentacionbtn = new javax.swing.JButton();
        contenedor = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        Boton_Aceptar = new javax.swing.JButton();

        setBackground(new java.awt.Color(85, 143, 178));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Zona de  Bienestar");

        GenerarRec_btn.setText("<html>Generar recomendaciones<br>preventivas</html>");
        GenerarRec_btn.setBorder(null);
        GenerarRec_btn.setContentAreaFilled(false);
        GenerarRec_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GenerarRec_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarRec_btnActionPerformed(evt);
            }
        });

        Rutina_actividades_btn.setText("<html>Ofrecer rutinas de <br>actividad física</html>");
        Rutina_actividades_btn.setBorder(null);
        Rutina_actividades_btn.setContentAreaFilled(false);
        Rutina_actividades_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Rutina_actividades_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Rutina_actividades_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rutina_actividades_btnActionPerformed(evt);
            }
        });

        Plan_de_alimentacionbtn.setText("<html>Sugerir plan de <br>alimentación </html>");
        Plan_de_alimentacionbtn.setBorder(null);
        Plan_de_alimentacionbtn.setContentAreaFilled(false);
        Plan_de_alimentacionbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Plan_de_alimentacionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plan_de_alimentacionbtnActionPerformed(evt);
            }
        });

        contenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        jButton2.setBackground(new java.awt.Color(218, 131, 136));
        jButton2.setText("<html>Cancelar y cerrar <br>el programa</html>");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Boton_Aceptar.setBackground(new java.awt.Color(138, 192, 102));
        Boton_Aceptar.setText("Aceptar");
        Boton_Aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_AceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Plan_de_alimentacionbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rutina_actividades_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenerarRec_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(Boton_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(GenerarRec_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rutina_actividades_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Plan_de_alimentacionbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2)
                    .addComponent(Boton_Aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void GenerarRec_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarRec_btnActionPerformed
        seleccionarBoton(GenerarRec_btn);
        Boton_Aceptar.setVisible(true);
    }//GEN-LAST:event_GenerarRec_btnActionPerformed

    private void Rutina_actividades_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rutina_actividades_btnActionPerformed
        seleccionarBoton(Rutina_actividades_btn);
        Boton_Aceptar.setVisible(true);
        
        contenedor.removeAll();
        contenedor.setLayout(new java.awt.BorderLayout());
        
        ConsejoRutinaFisica panelRutina = new ConsejoRutinaFisica(contenedor);  
        contenedor.add(panelRutina,java.awt.BorderLayout.CENTER);
        
        contenedor.revalidate();
        contenedor.repaint();       
    }//GEN-LAST:event_Rutina_actividades_btnActionPerformed

    private void Plan_de_alimentacionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plan_de_alimentacionbtnActionPerformed
        seleccionarBoton(Plan_de_alimentacionbtn);
        Boton_Aceptar.setVisible(true);
        
        contenedor.removeAll();
        contenedor.setLayout(new java.awt.BorderLayout());
        
        PlanAlimentaciónSalud panelAlimentación = new PlanAlimentaciónSalud(contenedor); 
        contenedor.add(panelAlimentación,java.awt.BorderLayout.CENTER);
        
        contenedor.revalidate();
        contenedor.repaint(); 
    }//GEN-LAST:event_Plan_de_alimentacionbtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int valor=JOptionPane.showConfirmDialog(null,"¿Deseas cancelar y cerrar todo?","Alerta",JOptionPane.YES_NO_OPTION);
        if(valor==0){
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Boton_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_AceptarActionPerformed
        int valor=JOptionPane.showConfirmDialog(null,"¿Deseas realizar esta operacion?",
            "Alerta",JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_Boton_AceptarActionPerformed
private void seleccionarBoton(JButton boton) { 
    if (boton == null) return; // Seguridad

    // Restaura el botón anterior
    if (botonSeleccionadoActual != null) {
        botonSeleccionadoActual.setBackground(COLOR_POR_DEFECTO);
        botonSeleccionadoActual.setOpaque(false);
        botonSeleccionadoActual.setContentAreaFilled(false);
    }

    // Selecciona el nuevo botón
    boton.setBackground(COLOR_SELECCIONADO);
    boton.setContentAreaFilled(true);
    boton.setOpaque(true);
    botonSeleccionadoActual = boton;
}
private void configurarBotones() {
    // Lista de todos los botones que cambiarán de color
    JButton[] botones = {
        GenerarRec_btn,
        Plan_de_alimentacionbtn,
        Rutina_actividades_btn
    };

    for (JButton boton : botones) {
        boton.setOpaque(false); 
        boton.setBorderPainted(false); 
        boton.setContentAreaFilled(false);
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Aceptar;
    private javax.swing.JButton GenerarRec_btn;
    private javax.swing.JButton Plan_de_alimentacionbtn;
    private javax.swing.JButton Rutina_actividades_btn;
    private javax.swing.JPanel contenedor;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
