/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

public class PlanAlimentaciónSalud extends javax.swing.JPanel {

    private javax.swing.JPanel contenedorPrincipal;

    public PlanAlimentaciónSalud(javax.swing.JPanel contenedorPrincipal) {
        this.contenedorPrincipal = contenedorPrincipal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboPlanes = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPlan = new javax.swing.JTextArea();
        REGRESAR_BTN = new javax.swing.JButton();
        REA_PLAN = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 175, 185));
        setPreferredSize(new java.awt.Dimension(578, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PLAN DE ALIMENTACIÓN SALUDABLE");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));

        comboPlanes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plan N1-RE", "Plan N2-EyQ", "Plan N3-AI", "Plan N4-ORH", "Plan N5-SMC" }));
        comboPlanes.setToolTipText("Eliga en base a las iniciales de su rutina fisica asignada");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Selecciona el tipo de Plan de Alimentación:");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Detalles del plan sugerido:");

        txtPlan.setColumns(20);
        txtPlan.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        txtPlan.setRows(5);
        jScrollPane1.setViewportView(txtPlan);

        REGRESAR_BTN.setBackground(new java.awt.Color(168, 218, 220));
        REGRESAR_BTN.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        REGRESAR_BTN.setText("REGRESAR");
        REGRESAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGRESAR_BTNActionPerformed(evt);
            }
        });

        REA_PLAN.setBackground(new java.awt.Color(168, 218, 220));
        REA_PLAN.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        REA_PLAN.setText("Realizar Plan");
        REA_PLAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REA_PLANActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 204, 204));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("¡En base a la rutina previamente seleccionada!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(comboPlanes, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(REA_PLAN, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(REGRESAR_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboPlanes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(REGRESAR_BTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(REA_PLAN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void REGRESAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGRESAR_BTNActionPerformed
        contenedorPrincipal.removeAll();
        contenedorPrincipal.setLayout(new java.awt.BorderLayout());

        ConsejoRutinaFisica panelConsejo = new ConsejoRutinaFisica(contenedorPrincipal);
        contenedorPrincipal.add(panelConsejo, java.awt.BorderLayout.CENTER); 

        contenedorPrincipal.revalidate();
        contenedorPrincipal.repaint(); 
    }//GEN-LAST:event_REGRESAR_BTNActionPerformed

    private void REA_PLANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REA_PLANActionPerformed
        String seleccion = comboPlanes.getSelectedItem().toString();
        String plan = "";

        switch (seleccion) {
            case "Plan N1-RE" ->
                plan = """
            -PLAN NUTRICIONAL PARA REHABILITACIÓN FÍSICA

            *Alimentos ricos en proteínas: pollo, pescado, huevos, legumbres.
            *Frutas y verduras con vitamina C: cítricos, pimientos, brócoli.
            *Grasas saludables: aguacate, nueces, aceite de oliva.
            *Evitar ultraprocesados y azúcares añadidos.
            *Mínimo 8 vasos de agua al día.
            """;

            case "Plan N2-EyN" ->
                plan = """
            -PLAN PARA NEUROPLASTICIDAD Y EQUILIBRIO

            *Omega-3: pescado azul, nueces, semillas de chía.
            *Vegetales de hoja verde: espinaca, kale.
            *Antioxidantes: arándanos, cúrcuma, cacao.
            *Evitar grasas trans y azúcares.
            *Hidratación adecuada para función cerebral.
            """;

            case "Plan N3-AI" ->
                plan = """
            -PLAN ANTIINFLAMATORIO INTESTINAL

            *Fermentados: yogur natural, kéfir, chucrut.
            *Fibras solubles: avena, manzana, plátano.
            *Proteínas magras cocidas al vapor.
            *Evitar gluten, lácteos enteros, picantes.
            *Agua tibia durante el día.
            """;

            case "Plan N4-ORH" ->
                plan = """
            -PLAN HEPÁTICO DE REGENERACIÓN Y OXIGENACIÓN

            *Vegetales crucíferos: brócoli, coliflor, repollo.
            *Agua con limón por las mañanas.
            *Cúrcuma y ajo como condimentos.
            *Evitar frituras, grasas saturadas, alcohol.
            *2 litros de agua con infusiones depurativas.
            """;

            case "Plan N5-SMC" ->
                plan = """
            -PLAN PARA SALUD METABÓLICA Y CARDIOVASCULAR

            *Frutas, verduras, granos integrales y legumbres.
            * Aceite de oliva como grasa principal.
            *Proteínas magras: pollo sin piel, pescado, tofu.
            *Limitar sal, azúcares simples y harinas blancas.
            *Beber agua natural, evitar bebidas azucaradas. 
            """;

            default ->
                plan = "⚠️ Seleccione un plan válido.";
        }

        txtPlan.setText(plan);

    }//GEN-LAST:event_REA_PLANActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton REA_PLAN;
    private javax.swing.JButton REGRESAR_BTN;
    private javax.swing.JComboBox<String> comboPlanes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtPlan;
    // End of variables declaration//GEN-END:variables
}
