
package Vista;

import Controlador.CRUDCita;
import Controlador.CancelarPagoCommand;
import Controlador.CitaFactory;
import Controlador.CommandPago;
import Controlador.CommandRealizarCita;
import Controlador.RealizarCitaCommand;
import Modelo.Cita;
import Modelo.Pago;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

public class PrecioEM2 extends javax.swing.JPanel {
    //Panel3
private Cita cita;
private Pago pago;
private javax.swing.JPanel panelPadre;
    public class NodoBP {

        String nombre; 
        String num_boleta;
        String monto_pagado;
        String estado_pago;
        String metodo_pago;

        NodoBP sig;

        public NodoBP(String nom, String nboleta, String metp, String montp, String ep) {
            nombre = nom;
            num_boleta = nboleta;
            metodo_pago = metp;
            monto_pagado = montp;
            estado_pago = ep;
        }
    }

    public NodoBP ini, fin;
    public NodoBP pFound;
    public PrecioEM2(Cita cita,javax.swing.JPanel panelPadre) {
        initComponents();
        this.cita=cita;
        this.panelPadre=panelPadre;
        Preciotxt.setEditable(false);
        EstadoPago.setEditable(false);
        double precio = cita.getPrecio();
        Preciotxt.setText(String.valueOf(precio));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        METODOPAGO = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        MontoP = new javax.swing.JTextField();
        GUARDAR = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        CodigoB = new javax.swing.JTextField();
        RESTAURAR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BOLETA = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        Preciotxt = new javax.swing.JTextField();
        EstadoPago = new javax.swing.JTextField();
        imagen1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Regresarbtn = new javax.swing.JButton();
        CancelarPago = new javax.swing.JButton();

        setBackground(new java.awt.Color(142, 236, 245));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(42, 157, 143));
        jLabel3.setText("Estado del Pago:");

        METODOPAGO.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        METODOPAGO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECCIONE--", "Yape", "Tarjeta Credito", "Transferencia", "Efectivo" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 34)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(42, 157, 143));
        jLabel1.setText("Zona de Pago");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(42, 157, 143));
        jLabel2.setText("Método de Pago:");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(42, 157, 143));
        jLabel4.setText("Monto Pagado:");

        MontoP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        MontoP.setToolTipText("En caso de pagar por tarjeta o un con alguna billetera digital coloque el precio exacto.");
        MontoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MontoPActionPerformed(evt);
            }
        });

        GUARDAR.setBackground(new java.awt.Color(168, 218, 220));
        GUARDAR.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        GUARDAR.setText("Realizar Cita");
        GUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUARDARActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(42, 157, 143));
        jLabel5.setText("Codigo Boleta: ");

        CodigoB.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        CodigoB.setToolTipText("En base a los 2 primeros caracteres de tu Nombre,Apellido,DNI,Area de la Consulta junto con el año de la cita(Sin espacios y todo en Mayuscula)\n");
        CodigoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoBActionPerformed(evt);
            }
        });

        RESTAURAR.setBackground(new java.awt.Color(168, 218, 220));
        RESTAURAR.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        RESTAURAR.setText("LIMPIAR");
        RESTAURAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESTAURARActionPerformed(evt);
            }
        });

        BOLETA.setColumns(20);
        BOLETA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BOLETA.setRows(5);
        jScrollPane1.setViewportView(BOLETA);

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(42, 157, 143));
        jLabel8.setText("Precio");

        Preciotxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Preciotxt.setToolTipText("En base a los 2 primeros caracteres de tu Nombre,Apellido,DNI,Area de la Consulta junto con el año de la cita(Sin espacios y todo en Mayuscula)\n");

        EstadoPago.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        EstadoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoPagoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(42, 157, 143));
        jLabel6.setText("Resumen");

        Regresarbtn.setBackground(new java.awt.Color(168, 218, 220));
        Regresarbtn.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Regresarbtn.setText("REGRESAR");
        Regresarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarbtnActionPerformed(evt);
            }
        });

        CancelarPago.setBackground(new java.awt.Color(168, 218, 220));
        CancelarPago.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        CancelarPago.setText("Cancelar Pago");
        CancelarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(GUARDAR, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RESTAURAR, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Regresarbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CancelarPago))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Preciotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CodigoB, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(MontoP, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(METODOPAGO, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(EstadoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imagen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Preciotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CodigoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(METODOPAGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(MontoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EstadoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GUARDAR)
                    .addComponent(RESTAURAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Regresarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MontoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MontoPActionPerformed

        double monto=Double.parseDouble(MontoP.getText());
        double precio=Double.parseDouble(Preciotxt.getText());
        if(monto>=precio){
            EstadoPago.setText("Pagado");
        }
        if(monto<precio){
            EstadoPago.setText("Pendiente");
        }
    }//GEN-LAST:event_MontoPActionPerformed

    private void GUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUARDARActionPerformed
        String nom = cita.getNombre_Completo();
        String nboleta = CodigoB.getText();
        String metp = METODOPAGO.getSelectedItem().toString();
        String montp = MontoP.getText();
        String ep = EstadoPago.getText();

        ini = InsertarInicio(ini, nom, nboleta, metp, montp, ep);

        if(CodigoB.getText().equals("")||METODOPAGO.getSelectedItem().equals("--SELECCIONE--") ||MontoP.getText().equals("")){
            JOptionPane.showMessageDialog(null,"No se logro realizar la cita con exito.No puede dejar nada en blanco");
        }else{
            double monto=Double.parseDouble(MontoP.getText());
            double precio=Double.parseDouble(Preciotxt.getText());
            if(monto<precio){
                ConfirmarCita();
                JOptionPane.showMessageDialog(null,"Recuerde pagar lo que le falta al momento de ir a su cita o por nuestro numero de cuenta "
                    + ".De lo contrario sera denunciado con las autoridades ");
            }else{
                ConfirmarCita();
                LimpiarEntradas();
                VerDatos();
            }
        }
    }//GEN-LAST:event_GUARDARActionPerformed
   private void ConfirmarCita(){
      /*Comando para obtener el DNI del medico y usarlo en el setter*/
      String nboleta = CodigoB.getText();
      String metp = METODOPAGO.getSelectedItem().toString();
      String montp = MontoP.getText();
      String ep = EstadoPago.getText();
      pago.setCodigo_Boleta(nboleta);
      pago.setMetodo_de_Pago(metp);
      pago.setMonto_de_Pago(Double.valueOf(montp));
      pago.setEstado_de_Pago(ep);
      CommandRealizarCita cmd = new RealizarCitaCommand(cita, pago);
      try {
        cmd.execute();
        JOptionPane.showMessageDialog(null, "¡Cita agendada y pago procesado!");
      } catch (HeadlessException ex) {
        cmd.undo();
      }
      }
    private void CodigoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoBActionPerformed

    private void RESTAURARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESTAURARActionPerformed
        LimpiarEntradas();
        METODOPAGO.setSelectedIndex(0);
    }//GEN-LAST:event_RESTAURARActionPerformed
    void Encabezado() {
        BOLETA.setFont(new Font("monospaced", Font.PLAIN, 12));
        BOLETA.setText("");

        BOLETA.append("");
        BOLETA.append("--------------------------BOLETA DEL HOSPITAL SALU FORMA----------------------------------\n");
        BOLETA.append(" NOMBRE COMPLETO   CODIGO BOLETA   METODO DE PAGO  MONTO PAGADO    ESTADO PAGO\n");
        BOLETA.append(" -----------------------------------------------------------------------------------------\n");
    }
void VerDatos() {
        String nom, ape, nboleta, metp, montp, ep;
        PrecioEM2.NodoBP aux = ini;

        Encabezado();

        while (aux != null) {
            nom = aux.nombre;
            nboleta = aux.num_boleta;
            metp = aux.metodo_pago;
            montp = aux.monto_pagado;
            ep = aux.estado_pago;

            for (int i = nom.length(); i < 12; i++) {
                nom = nom + " ";
            }
            for (int i = nboleta.length(); i < 18; i++) {
                nboleta = nboleta + " ";
            }
            for (int i = metp.length(); i < 18; i++) {
                metp = metp + " ";
            }
            for (int i = montp.length(); i < 12; i++) {
                montp = montp + " ";
            }
            for (int i = ep.length(); i < 12; i++) {
                ep = ep + " ";
            }

            BOLETA.append(nom+ nboleta + metp + montp + ep + "\n");
            aux = aux.sig;
        }
    }
    void LimpiarEntradas() {
    CodigoB.setText("");
    MontoP.setText("");
    METODOPAGO.setSelectedIndex(0);
    EstadoPago.setText("");
}
NodoBP InsertarInicio(NodoBP inicio, String nom, String nboleta, String metp, String montp,String ep) {
        NodoBP nuevo = new NodoBP(nom,nboleta, metp, montp, ep);
        nuevo.sig = inicio;
        inicio = nuevo;
        return inicio;
}
    private void EstadoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoPagoActionPerformed

    }//GEN-LAST:event_EstadoPagoActionPerformed

    private void RegresarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarbtnActionPerformed
        cambiaraConf_c2();
    }//GEN-LAST:event_RegresarbtnActionPerformed

    private void CancelarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarPagoActionPerformed
         String codigoBoleta = JOptionPane.showInputDialog(this, "Ingrese el código de la boleta a cancelar:");

        if (codigoBoleta != null && !codigoBoleta.trim().isEmpty()) {
            int confirmacion = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro que desea cancelar el pago con código: " + codigoBoleta + "?",
                    "Confirmar cancelación", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                // Crear el objeto Pago con el código ingresado
                Pago pago = new Pago();
                pago.setCodigo_Boleta(codigoBoleta);

                // Crear el comando y ejecutarlo
                CommandPago cmdCancelar = new CancelarPagoCommand(pago, cita);
                try {
                    cmdCancelar.execute();
                    JOptionPane.showMessageDialog(this, "Pago cancelado exitosamente.");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error al cancelar el pago: " + e.getMessage());
                }
            }  
        } else { 
            JOptionPane.showMessageDialog(this, "Debe ingresar un código de boleta válido.");
        }  

    }//GEN-LAST:event_CancelarPagoActionPerformed
   private void cambiaraConf_c2() {
                // Obtener el contenedor padre (JFrame o JPanel principal)
        java.awt.Container parent = this.getParent();
        
        // Remover este panel
        parent.remove(this);
        
        // Crear y agregar el nuevo panel
        Confirmar_Cita2 conf2= new Confirmar_Cita2(cita, panelPadre);
        parent.add(conf2,BorderLayout.CENTER);
        
        // Actualizar la interfaz
        parent.revalidate();
        parent.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea BOLETA;
    private javax.swing.JButton CancelarPago;
    private javax.swing.JTextField CodigoB;
    private javax.swing.JTextField EstadoPago;
    private javax.swing.JButton GUARDAR;
    private javax.swing.JComboBox<String> METODOPAGO;
    private javax.swing.JTextField MontoP;
    private javax.swing.JTextField Preciotxt;
    private javax.swing.JButton RESTAURAR;
    private javax.swing.JButton Regresarbtn;
    private javax.swing.JLabel imagen1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
