
package Vista;

import Controlador.ModuloProxy;
import Modelo.Cita;
import Modelo.Paciente;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author LAB-USR-LNORTE
 */
public class Ventana_Principal2 extends javax.swing.JFrame {
    private final String rolUsuario;
    private Cita cita;
    public Ventana_Principal2(String rolUsuario,Cita cita) {
        initComponents();
        this.rolUsuario = rolUsuario;
        setLocationRelativeTo(null);
        setTitle("Ventana principal");
        this.cita=cita;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Modulo_Pacientes = new javax.swing.JButton();
        BienestarBtn = new javax.swing.JButton();
        Recordatorio_Salud = new javax.swing.JButton();
        Boton_atajo = new javax.swing.JButton();
        contenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(85, 143, 178));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        Modulo_Pacientes.setText("PACIENTES");
        Modulo_Pacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Modulo_Pacientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Modulo_Pacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modulo_PacientesActionPerformed(evt);
            }
        });
        jPanel2.add(Modulo_Pacientes);

        BienestarBtn.setText("CONSEJOS DE BIENESTAR");
        BienestarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BienestarBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BienestarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BienestarBtnActionPerformed(evt);
            }
        });
        jPanel2.add(BienestarBtn);

        Recordatorio_Salud.setText("RECORDATORIOS DE SALUD");
        Recordatorio_Salud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Recordatorio_Salud.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Recordatorio_Salud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Recordatorio_SaludActionPerformed(evt);
            }
        });
        jPanel2.add(Recordatorio_Salud);

        Boton_atajo.setText("AGENDAR CITA");
        Boton_atajo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_atajo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton_atajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_atajoActionPerformed(evt);
            }
        });
        jPanel2.add(Boton_atajo);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 50));

        contenedor.setPreferredSize(new java.awt.Dimension(830, 649));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        jPanel1.add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 830, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void Boton_atajoActionPerformed(java.awt.event.ActionEvent evt) {                                            

        ModuloProxy proxy = new ModuloProxy(this.rolUsuario, "Pacientes",cita);
        JPanel panelPermitido = proxy.obtenerPanel();
        if (panelPermitido instanceof PanelPacientes) {
        PanelPacientes panelPacientes = (PanelPacientes) panelPermitido;
        panelPacientes.mostrarPanelCitas();
        }
        contenedor.removeAll();
        contenedor.setLayout(new BorderLayout());
        contenedor.add(panelPermitido, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }                                           

    private void Recordatorio_SaludActionPerformed(java.awt.event.ActionEvent evt) {                                                   

        ModuloProxy proxy = new ModuloProxy(this.rolUsuario, "Recordatorios",cita);
        JPanel panelPermitido = proxy.obtenerPanel();
        if(panelPermitido instanceof PanelNotificaciones){
            PanelNotificaciones panNoti=(PanelNotificaciones) panelPermitido;
            panNoti.AgregarPaciente(new Paciente());
            panNoti.AgregarPaciente2(new Paciente());
        }
        contenedor.removeAll();
        contenedor.setLayout(new BorderLayout());
        contenedor.add(panelPermitido, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }                                                  

    private void BienestarBtnActionPerformed(java.awt.event.ActionEvent evt) {                                             

        ModuloProxy proxy = new ModuloProxy(this.rolUsuario, "Consejos",cita);

        JPanel panelPermitido = proxy.obtenerPanel();
        contenedor.removeAll();
        contenedor.setLayout(new BorderLayout());
        contenedor.add(panelPermitido, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }                                            

    private void Modulo_PacientesActionPerformed(java.awt.event.ActionEvent evt) {                                                 

        cita=new Cita();
        ModuloProxy proxy = new ModuloProxy(this.rolUsuario, "Pacientes",cita);
        JPanel panelPermitido = proxy.obtenerPanel();
        contenedor.removeAll();
        contenedor.setLayout(new BorderLayout());
        contenedor.add(panelPermitido, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }                                                

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify                     
    private javax.swing.JButton BienestarBtn;
    private javax.swing.JButton Boton_atajo;
    private javax.swing.JButton Modulo_Pacientes;
    private javax.swing.JButton Recordatorio_Salud;
    private javax.swing.JPanel contenedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration                   
}
